name: Haskell CI

# Big thanks to https://markkarpov.com/post/github-actions-for-haskell-ci.html

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  cabal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['7.10', '8.0', '8.2', '8.4', '8.6', '8.8', '8.10']
      fail-fast: false
    env:
      CABAL_ARGS: "--enable-tests --enable-benchmarks"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}

    - run: cabal update
    - run: cabal freeze $CABAL_ARGS

    - uses: actions/cache@v2
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Install dependencies
      run: cabal build $CABAL_ARGS --only-dependencies
    - run: cabal build $CABAL_ARGS all
    - run: cabal test $CABAL_ARGS all
    - run: cabal haddock $CABAL_ARGS all
    - run: cabal sdist $CABAL_ARGS all
